// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "7df73a7c-abd1-42e1-9989-37a756a0047d";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


float humidityLevel;
float temperatureLevel;
int garbageLevel;
int smokeLevel;
bool led;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humidityLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperatureLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(garbageLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(smokeLevel, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(led, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
